2022-07-02 16:46:15 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-02 16:53:35 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-02 17:58:18 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\book_store\settings.py changed, reloading.
2022-07-02 19:51:26 WARNING-Method Not Allowed: /addbook/
2022-07-02 19:56:30 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 20:00:12 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 20:02:41 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 20:02:43 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
2022-07-02 20:02:52 WARNING-Method Not Allowed: /addbook/
2022-07-02 20:02:59 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
2022-07-02 20:13:44 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-02 20:13:45 WARNING-Method Not Allowed: /addbook/
2022-07-02 20:14:40 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
2022-07-02 20:17:36 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 20:17:50 WARNING-Method Not Allowed: /addbook/
2022-07-02 20:18:51 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
2022-07-02 20:18:55 WARNING-Method Not Allowed: /login/
2022-07-02 20:18:56 WARNING-Method Not Allowed: /addbook/
2022-07-02 20:19:34 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
2022-07-02 21:17:14 WARNING-Method Not Allowed: /login/
2022-07-02 21:47:24 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\urls.py changed, reloading.
2022-07-02 21:47:32 WARNING-Method Not Allowed: /addbook/
2022-07-02 21:50:33 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
2022-07-02 22:04:28 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-02 22:04:58 WARNING-Method Not Allowed: /login/
2022-07-02 22:07:15 WARNING-Method Not Allowed: /addbook/
2022-07-02 22:07:45 ERROR-Log Error Message
2022-07-02 22:08:04 ERROR-Log Error Message
2022-07-02 22:12:40 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-02 22:13:06 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 28, in token_decode
    data = decode(token, SECRET_KEY, 'HS256')
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\jwt\api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\jwt\api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\jwt\api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\jwt\api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
2022-07-02 22:14:46 WARNING-Method Not Allowed: /addbook/
2022-07-02 22:17:34 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-02 22:17:54 ERROR-Log Error Message
2022-07-02 22:19:32 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:19:57 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 28, in token_decode
    data = decode(token, SECRET_KEY, 'HS256')
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\jwt\api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\jwt\api_jwt.py", line 116, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\jwt\api_jwt.py", line 152, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\jwt\api_jwt.py", line 187, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
2022-07-02 22:20:52 WARNING-Method Not Allowed: /addbook/
2022-07-02 22:20:55 WARNING-Method Not Allowed: /addbook/
2022-07-02 22:20:56 WARNING-Method Not Allowed: /addbook/
2022-07-02 22:21:17 WARNING-Method Not Allowed: /addbook/
2022-07-02 22:21:30 WARNING-Method Not Allowed: /addbook/
2022-07-02 22:21:53 ERROR-Log Error Message
2022-07-02 22:22:51 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:23:09 ERROR-Log Error Message
2022-07-02 22:28:23 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\book_store\settings.py changed, reloading.
2022-07-02 22:29:08 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\book_store\settings.py changed, reloading.
2022-07-02 22:30:23 WARNING-Method Not Allowed: /addbook/
2022-07-02 22:30:45 ERROR-Log Error Message
2022-07-02 22:32:15 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:32:40 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:33:08 ERROR-Log Error Message
2022-07-02 22:33:38 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:33:57 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
TypeError: post() takes 2 positional arguments but 3 were given
2022-07-02 22:34:36 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:34:40 ERROR-Log Error Message
2022-07-02 22:35:05 ERROR-Log Error Message
2022-07-02 22:35:56 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:36:17 ERROR-Log Error Message
2022-07-02 22:39:02 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:40:25 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:40:46 ERROR-Log Error Message
2022-07-02 22:41:57 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:42:25 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:42:46 ERROR-Log Error Message
2022-07-02 22:43:30 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:43:46 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 17, in post
    superuser = Book.validate_superuser(kwargs['user_id'])
KeyError: 'user_id'
2022-07-02 22:44:24 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:44:29 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 17, in post
    superuser = Book.validate_superuser(kwargs['id'])
KeyError: 'id'
2022-07-02 22:44:36 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 17, in post
    superuser = Book.validate_superuser(kwargs['id'])
KeyError: 'id'
2022-07-02 22:45:19 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:46:06 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:46:10 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 28, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 22:46:45 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:46:50 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 28, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 22:46:55 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 28, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 22:49:13 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:49:16 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 29, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 22:49:46 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:49:49 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 30, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 22:50:26 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:50:30 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 22:51:29 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:55:38 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 125, in _wrapped_view
    result = middleware.process_request(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\middleware\csrf.py", line 388, in process_request
    csrf_token = self._get_token(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\middleware\csrf.py", line 229, in _get_token
    cookie_token = request.COOKIES[settings.CSRF_COOKIE_NAME]
AttributeError: 'AddBookAPI' object has no attribute 'COOKIES'
2022-07-02 22:57:15 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:57:19 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 22:57:45 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:57:52 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 22:58:22 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 22:58:25 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 22:58:52 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 23:02:02 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\book_store\settings.py changed, reloading.
2022-07-02 23:02:21 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\book_store\settings.py changed, reloading.
2022-07-02 23:02:44 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\book_store\settings.py changed, reloading.
2022-07-02 23:02:51 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 23:02:58 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 23:05:12 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\book_store\settings.py changed, reloading.
2022-07-02 23:05:20 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 23:07:00 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 23:07:05 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 23:07:29 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 23:07:34 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 23:08:15 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 23:08:44 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 34, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 23:10:44 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-02 23:15:48 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\serializers.py changed, reloading.
2022-07-02 23:16:02 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 23:17:29 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 23:18:28 WARNING-Bad Request: /addbook/
2022-07-02 23:18:50 WARNING-Bad Request: /addbook/
2022-07-02 23:19:27 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 32, in post
    book = Book.objects.create(**data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 512, in create
    obj = self.model(**kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\base.py", line 559, in __init__
    raise TypeError(
TypeError: Book() got an unexpected keyword argument 'csrfmiddlewaretoken'
2022-07-02 23:21:56 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-02 23:26:01 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-02 23:26:10 WARNING-Method Not Allowed: /login/
2022-07-02 23:26:15 WARNING-Not Found: /
2022-07-02 23:26:22 WARNING-Method Not Allowed: /register/
2022-07-02 23:26:43 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-02 23:27:24 ERROR-Log Error Message
2022-07-02 23:28:40 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-02 23:28:53 ERROR-Log Error Message
2022-07-02 23:31:56 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-02 23:32:24 ERROR-Log Error Message
2022-07-02 23:34:58 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-02 23:35:09 ERROR-Log Error Message
2022-07-02 23:35:53 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-02 23:37:09 ERROR-Log Error Message
2022-07-02 23:37:35 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-02 23:37:44 ERROR-Log Error Message
2022-07-02 23:38:34 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-02 23:39:06 ERROR-Log Error Message
2022-07-02 23:39:25 ERROR-Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-03 00:01:06 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-03 00:01:07 WARNING-Method Not Allowed: /addbook/
2022-07-03 00:06:28 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 00:10:37 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\serializers.py changed, reloading.
2022-07-03 00:13:52 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\serializers.py changed, reloading.
2022-07-03 00:14:11 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\serializers.py changed, reloading.
2022-07-03 19:11:51 WARNING-Method Not Allowed: /register/
2022-07-03 19:11:51 WARNING-Not Found: /favicon.ico
2022-07-03 19:18:38 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-03 19:23:09 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-03 19:25:09 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-03 19:25:16 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-03 19:27:21 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-03 19:27:58 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-03 19:31:49 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-03 19:32:40 ERROR-Log Error Message
2022-07-03 19:35:09 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-03 19:38:10 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-03 19:38:32 ERROR-Log Error Message
2022-07-03 19:39:13 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-03 19:39:41 ERROR-Log Error Message
2022-07-03 19:47:08 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-03 20:35:44 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-03 20:43:21 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-03 20:54:12 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\serializers.py changed, reloading.
2022-07-03 21:05:08 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 21:22:52 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 21:25:53 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 21:25:54 INFO-Watching for file changes with StatReloader
2022-07-03 21:25:59 WARNING-Method Not Allowed: /addbook/
2022-07-03 21:26:16 WARNING-Method Not Allowed: /login/
2022-07-03 21:26:24 WARNING-Method Not Allowed: /addbook/
2022-07-03 21:27:40 WARNING-Method Not Allowed: /addbook/
2022-07-03 21:28:52 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 21:28:53 INFO-Watching for file changes with StatReloader
2022-07-03 21:28:58 ERROR-Log Error Message
2022-07-03 21:29:34 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 21:29:35 INFO-Watching for file changes with StatReloader
2022-07-03 21:29:51 ERROR-Log Error Message
2022-07-03 21:31:59 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 21:32:00 INFO-Watching for file changes with StatReloader
2022-07-03 22:08:06 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 22:08:06 INFO-Watching for file changes with StatReloader
2022-07-03 22:09:00 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 22, in post
    book = Book.check_if_book_exists(serialized_data.data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py", line 55, in check_if_book_exists
    book = Book.create_book(validated_data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py", line 38, in create_book
    book = Book.objects.create_user(validated_data['name'],
AttributeError: 'Manager' object has no attribute 'create_user'
2022-07-03 22:12:30 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:12:31 INFO-Watching for file changes with StatReloader
2022-07-03 22:12:45 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:12:46 INFO-Watching for file changes with StatReloader
2022-07-03 22:13:21 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:13:22 INFO-Watching for file changes with StatReloader
2022-07-03 22:14:15 WARNING-Method Not Allowed: /addbook/
2022-07-03 22:14:25 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column books_book.password does not exist
LINE 1: SELECT "books_book"."id", "books_book"."password", "books_bo...
                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 22, in post
    book = Book.check_if_book_exists(serialized_data.data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py", line 53, in check_if_book_exists
    book = Book.objects.filter(name=book_name).first()
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 753, in first
    for obj in (self if self.ordered else self.order_by("pk"))[:1]:
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 320, in __iter__
    self._fetch_all()
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column books_book.password does not exist
LINE 1: SELECT "books_book"."id", "books_book"."password", "books_bo...
                                  ^

2022-07-03 22:16:34 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:16:34 INFO-Watching for file changes with StatReloader
2022-07-03 22:25:05 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:25:06 INFO-Watching for file changes with StatReloader
2022-07-03 22:26:45 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 22:26:46 INFO-Watching for file changes with StatReloader
2022-07-03 22:26:47 WARNING-Method Not Allowed: /addbook/
2022-07-03 22:26:51 WARNING-Method Not Allowed: /addbook/
2022-07-03 22:27:32 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 26, in post
    serialized_data.save()
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\serializers.py", line 198, in save
    assert not hasattr(self, '_data'), (
AssertionError: You cannot call `.save()` after accessing `serializer.data`.If you need to access data before committing to the database then inspect 'serializer.validated_data' instead. 
2022-07-03 22:28:44 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 22:28:45 INFO-Watching for file changes with StatReloader
2022-07-03 22:28:57 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 26, in post
    serializer.save()
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\serializers.py", line 198, in save
    assert not hasattr(self, '_data'), (
AssertionError: You cannot call `.save()` after accessing `serializer.data`.If you need to access data before committing to the database then inspect 'serializer.validated_data' instead. 
2022-07-03 22:29:51 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 22:29:51 INFO-Watching for file changes with StatReloader
2022-07-03 22:29:53 WARNING-Method Not Allowed: /addbook/
2022-07-03 22:30:03 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-03 22:31:12 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 22:31:13 INFO-Watching for file changes with StatReloader
2022-07-03 22:32:12 WARNING-Method Not Allowed: /addbook/
2022-07-03 22:32:56 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-03 22:35:52 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 22:35:53 INFO-Watching for file changes with StatReloader
2022-07-03 22:36:48 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-03 22:39:42 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 22:39:43 INFO-Watching for file changes with StatReloader
2022-07-03 22:40:41 WARNING-Method Not Allowed: /addbook/
2022-07-03 22:40:49 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-03 22:40:53 WARNING-Method Not Allowed: /addbook/
2022-07-03 22:42:15 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 22:42:16 INFO-Watching for file changes with StatReloader
2022-07-03 22:42:54 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-03 22:43:12 WARNING-Method Not Allowed: /addbook/
2022-07-03 22:48:52 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:48:53 INFO-Watching for file changes with StatReloader
2022-07-03 22:49:07 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-03 22:49:43 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:49:43 INFO-Watching for file changes with StatReloader
2022-07-03 22:51:46 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:51:47 INFO-Watching for file changes with StatReloader
2022-07-03 22:52:20 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:52:21 INFO-Watching for file changes with StatReloader
2022-07-03 22:53:39 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:53:39 INFO-Watching for file changes with StatReloader
2022-07-03 22:57:37 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 22:57:38 INFO-Watching for file changes with StatReloader
2022-07-03 23:02:00 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:02:01 INFO-Watching for file changes with StatReloader
2022-07-03 23:02:45 WARNING-Method Not Allowed: /addbook/
2022-07-03 23:02:56 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-03 23:21:19 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-03 23:21:20 INFO-Watching for file changes with StatReloader
2022-07-03 23:22:26 WARNING-Method Not Allowed: /addbook/
2022-07-03 23:23:01 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-03 23:25:55 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:25:56 INFO-Watching for file changes with StatReloader
2022-07-03 23:33:47 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:33:47 INFO-Watching for file changes with StatReloader
2022-07-03 23:36:16 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:36:17 INFO-Watching for file changes with StatReloader
2022-07-03 23:37:46 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:37:47 INFO-Watching for file changes with StatReloader
2022-07-03 23:38:03 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:38:03 INFO-Watching for file changes with StatReloader
2022-07-03 23:42:36 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:42:37 INFO-Watching for file changes with StatReloader
2022-07-03 23:43:32 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\urls.py changed, reloading.
2022-07-03 23:43:33 INFO-Watching for file changes with StatReloader
2022-07-03 23:44:00 ERROR-Internal Server Error: /getbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
TypeError: get() takes 2 positional arguments but 3 were given
2022-07-03 23:44:53 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:44:54 INFO-Watching for file changes with StatReloader
2022-07-03 23:50:40 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:50:41 INFO-Watching for file changes with StatReloader
2022-07-03 23:51:29 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:51:30 INFO-Watching for file changes with StatReloader
2022-07-03 23:52:18 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:52:18 INFO-Watching for file changes with StatReloader
2022-07-03 23:52:55 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:52:56 INFO-Watching for file changes with StatReloader
2022-07-03 23:53:14 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:53:15 INFO-Watching for file changes with StatReloader
2022-07-03 23:53:33 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:53:34 INFO-Watching for file changes with StatReloader
2022-07-03 23:54:53 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-03 23:54:54 INFO-Watching for file changes with StatReloader
2022-07-03 23:59:05 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\urls.py changed, reloading.
2022-07-03 23:59:06 INFO-Watching for file changes with StatReloader
2022-07-03 23:59:35 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\urls.py changed, reloading.
2022-07-03 23:59:35 INFO-Watching for file changes with StatReloader
2022-07-03 23:59:49 WARNING-Not Found: /getbook/2/
2022-07-04 00:00:02 WARNING-Not Found: /book/2/
2022-07-04 00:02:39 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 00:02:39 INFO-Watching for file changes with StatReloader
2022-07-04 00:02:43 WARNING-Not Found: /book/2/
2022-07-04 00:02:46 WARNING-Not Found: /book/2/
2022-07-04 00:02:47 WARNING-Not Found: /book/2/
2022-07-04 00:02:47 WARNING-Not Found: /book/2/
2022-07-04 00:02:47 WARNING-Not Found: /book/2/
2022-07-04 00:02:47 WARNING-Not Found: /book/2/
2022-07-04 00:02:48 WARNING-Not Found: /book/2/
2022-07-04 00:02:48 WARNING-Not Found: /book/2/
2022-07-04 00:02:48 WARNING-Not Found: /book/2/
2022-07-04 00:02:48 WARNING-Not Found: /book/2/
2022-07-04 00:03:48 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\urls.py changed, reloading.
2022-07-04 00:03:49 INFO-Watching for file changes with StatReloader
2022-07-04 00:04:33 WARNING-Not Found: /book/2/
2022-07-04 00:04:34 WARNING-Not Found: /book/2/
2022-07-04 00:04:55 ERROR-Internal Server Error: /book/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'id'
2022-07-04 00:05:19 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 00:05:19 INFO-Watching for file changes with StatReloader
2022-07-04 00:05:39 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 00:05:39 INFO-Watching for file changes with StatReloader
2022-07-04 00:06:12 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 00:06:13 INFO-Watching for file changes with StatReloader
2022-07-04 00:06:32 WARNING-Not Found: /book/2/
2022-07-04 00:08:12 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 00:08:13 INFO-Watching for file changes with StatReloader
2022-07-04 00:08:27 WARNING-Not Found: /book/1/
2022-07-04 00:08:32 WARNING-Not Found: /book/1/
2022-07-04 00:13:58 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 00:13:59 INFO-Watching for file changes with StatReloader
2022-07-04 08:16:41 INFO-Watching for file changes with StatReloader
2022-07-04 08:16:43 WARNING-Not Found: /
2022-07-04 08:16:43 WARNING-Not Found: /favicon.ico
2022-07-04 08:16:50 WARNING-Method Not Allowed: /addbook/
2022-07-04 08:17:27 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
2022-07-04 08:20:51 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-04 08:20:52 INFO-Watching for file changes with StatReloader
2022-07-04 08:24:58 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\models.py changed, reloading.
2022-07-04 08:24:59 INFO-Watching for file changes with StatReloader
2022-07-04 08:25:18 WARNING-Method Not Allowed: /login/
2022-07-04 08:26:56 WARNING-Method Not Allowed: /addbook/
2022-07-04 08:27:01 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
2022-07-04 08:32:28 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 08:32:28 INFO-Watching for file changes with StatReloader
2022-07-04 08:33:47 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 08:33:47 INFO-Watching for file changes with StatReloader
2022-07-04 08:33:49 WARNING-Method Not Allowed: /addbook/
2022-07-04 08:34:14 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
2022-07-04 08:34:20 WARNING-Method Not Allowed: /addbook/
2022-07-04 08:34:37 WARNING-Method Not Allowed: /addbook/
2022-07-04 08:38:31 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 08:38:32 INFO-Watching for file changes with StatReloader
2022-07-04 08:39:33 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\urls.py changed, reloading.
2022-07-04 08:39:34 INFO-Watching for file changes with StatReloader
2022-07-04 08:45:40 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 08:45:41 INFO-Watching for file changes with StatReloader
2022-07-04 08:46:54 ERROR-Internal Server Error: /book/1/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
TypeError: get() got multiple values for argument 'id'
2022-07-04 08:49:57 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py changed, reloading.
2022-07-04 08:49:58 INFO-Watching for file changes with StatReloader
2022-07-04 08:50:06 ERROR-Internal Server Error: /book/1/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 31, in token_decode
    return f(request, user_id, *args, **kwargs)
TypeError: get() got multiple values for argument 'id'
2022-07-04 08:50:08 ERROR-Internal Server Error: /book/1/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 31, in token_decode
    return f(request, user_id, *args, **kwargs)
TypeError: get() got multiple values for argument 'id'
2022-07-04 08:50:19 ERROR-Internal Server Error: /book/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 31, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 60, in get
    book = Book.objects.get(pk=id)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
books.models.Book.DoesNotExist: Book matching query does not exist.
2022-07-04 08:56:39 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 08:56:40 INFO-Watching for file changes with StatReloader
2022-07-04 08:56:43 ERROR-Internal Server Error: /book/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1988, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 31, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 62, in get
    book = Book.objects.get(pk=note_id)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 482, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1532, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1448, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1273, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1990, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '1d'.
2022-07-04 09:15:21 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 09:15:22 INFO-Watching for file changes with StatReloader
2022-07-04 09:15:34 WARNING-Method Not Allowed: /register/
2022-07-04 09:18:04 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-04 09:18:05 INFO-Watching for file changes with StatReloader
2022-07-04 09:22:42 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-04 09:22:43 INFO-Watching for file changes with StatReloader
2022-07-04 09:34:48 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-04 09:34:49 INFO-Watching for file changes with StatReloader
2022-07-04 09:35:13 ERROR-Log Error Message
2022-07-04 09:37:41 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-04 09:37:42 INFO-Watching for file changes with StatReloader
2022-07-04 09:37:52 ERROR-Log Error Message
2022-07-04 09:38:18 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-04 09:38:19 INFO-Watching for file changes with StatReloader
2022-07-04 09:38:31 ERROR-Log Error Message
2022-07-04 09:41:22 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-04 09:41:23 INFO-Watching for file changes with StatReloader
2022-07-04 09:41:45 ERROR-Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2022-07-04 09:46:35 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 09:46:36 INFO-Watching for file changes with StatReloader
2022-07-04 09:46:45 WARNING-Method Not Allowed: /register/
2022-07-04 09:47:29 ERROR-Log Error Message
2022-07-04 09:48:00 WARNING-Method Not Allowed: /register/
2022-07-04 09:48:05 WARNING-Method Not Allowed: /register/
2022-07-04 09:48:05 WARNING-Not Found: /favicon.ico
2022-07-04 09:48:06 WARNING-Method Not Allowed: /register/
2022-07-04 09:48:06 WARNING-Not Found: /favicon.ico
2022-07-04 09:48:30 ERROR-Log Error Message
2022-07-04 09:50:43 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 09:50:44 INFO-Watching for file changes with StatReloader
2022-07-04 09:51:55 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 09:51:56 INFO-Watching for file changes with StatReloader
2022-07-04 09:52:02 ERROR-Log Error Message
2022-07-04 09:55:32 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 09:55:33 INFO-Watching for file changes with StatReloader
2022-07-04 11:05:05 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 11:05:06 INFO-Watching for file changes with StatReloader
2022-07-04 11:07:01 ERROR-Log Error Message
2022-07-04 11:07:01 WARNING-Bad Request: /register/
2022-07-04 11:10:21 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 11:10:22 INFO-Watching for file changes with StatReloader
2022-07-04 11:10:38 ERROR-Log Error Message
2022-07-04 11:10:38 WARNING-Bad Request: /register/
2022-07-04 11:13:28 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-04 11:13:30 INFO-Watching for file changes with StatReloader
2022-07-04 11:13:43 ERROR-Log Error Message
2022-07-04 11:13:43 WARNING-Bad Request: /register/
2022-07-04 11:18:20 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\serializers.py changed, reloading.
2022-07-04 11:18:22 INFO-Watching for file changes with StatReloader
2022-07-04 11:18:29 ERROR-Log Error Message
2022-07-04 11:18:29 WARNING-Bad Request: /register/
2022-07-04 11:24:07 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 11:24:08 INFO-Watching for file changes with StatReloader
2022-07-04 11:24:42 ERROR-Log Error Message
2022-07-04 11:24:42 WARNING-Bad Request: /register/
2022-07-04 11:25:09 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 11:25:10 INFO-Watching for file changes with StatReloader
2022-07-04 11:29:26 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 11:29:28 INFO-Watching for file changes with StatReloader
2022-07-04 11:45:23 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\email.py changed, reloading.
2022-07-04 11:45:24 INFO-Watching for file changes with StatReloader
2022-07-04 11:57:37 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 11:57:38 INFO-Watching for file changes with StatReloader
2022-07-04 11:57:47 ERROR-Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py", line 26, in post
    urls = Mail.register_user(data={'email': user.email, 'username': user.username,
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\email.py", line 19, in register_user
    message = f'Hi {data["username"]}, ' \
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py", line 32, in post
    logger.logger.exception(e)
AttributeError: 'NoneType' object has no attribute 'exception'
2022-07-04 11:58:51 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 11:58:52 INFO-Watching for file changes with StatReloader
2022-07-04 11:59:00 ERROR-'url'
2022-07-04 11:59:00 WARNING-Bad Request: /register/
2022-07-04 12:02:18 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 12:02:19 INFO-Watching for file changes with StatReloader
2022-07-04 12:02:28 ERROR-'url'
2022-07-04 12:02:28 WARNING-Bad Request: /register/
2022-07-04 12:03:48 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\accounts\views.py changed, reloading.
2022-07-04 12:03:48 INFO-Watching for file changes with StatReloader
2022-07-04 14:40:54 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 14:40:54 INFO-Watching for file changes with StatReloader
2022-07-04 14:45:17 ERROR-Internal Server Error: /addbook
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\middleware\common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/addbook/?token=ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SjBiMnRsYmw5MGVYQmxJam9pWVdOalpYTnpJaXdpWlhod0lqb3hOalkxTlRRek16a3hMQ0pwWVhRaU9qRTJOVFk1TURNek9URXNJbXAwYVNJNklqZzNOVE0zTUdVeVpXVXlaVFF3T0dJNE1HVmxNRGRrTkdNME1XTXpaRGhqSWl3aWRYTmxjbDlwWkNJNk1UWjkuSk8tMTdJOFlaQkZtamRnZERYTjdDZUJVNXY0RWRmTTZNVENQTzJHN0VWTQ== (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2022-07-04 14:46:00 ERROR-Log Error Message
2022-07-04 14:46:57 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 14:46:58 INFO-Watching for file changes with StatReloader
2022-07-04 14:47:02 ERROR-Log Error Message
2022-07-04 14:47:42 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 14:47:43 INFO-Watching for file changes with StatReloader
2022-07-04 14:47:48 ERROR-Internal Server Error: /addbook/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\The Lie Lama\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\The Lie Lama\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\The Lie Lama\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\The Lie Lama\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AddBookSerializer is not JSON serializable
2022-07-04 14:49:26 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 14:49:27 INFO-Watching for file changes with StatReloader
2022-07-04 14:49:28 ERROR-Log Error Message
2022-07-04 14:51:42 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 14:51:42 INFO-Watching for file changes with StatReloader
2022-07-04 14:52:23 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 14:52:24 INFO-Watching for file changes with StatReloader
2022-07-04 14:52:32 ERROR-Log Error Message
2022-07-04 15:09:56 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:09:57 INFO-Watching for file changes with StatReloader
2022-07-04 15:09:58 ERROR-Log Error Message
2022-07-04 15:11:10 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:11:11 INFO-Watching for file changes with StatReloader
2022-07-04 15:12:13 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:12:14 INFO-Watching for file changes with StatReloader
2022-07-04 15:15:32 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:15:33 INFO-Watching for file changes with StatReloader
2022-07-04 15:17:15 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:17:16 INFO-Watching for file changes with StatReloader
2022-07-04 15:17:35 ERROR-Internal Server Error: /book/5/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 31, in token_decode
    return f(request, user_id, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'id'
2022-07-04 15:18:36 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:18:37 INFO-Watching for file changes with StatReloader
2022-07-04 15:20:04 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:20:05 INFO-Watching for file changes with StatReloader
2022-07-04 15:20:13 ERROR-Internal Server Error: /book/5/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 31, in token_decode
    return f(request, user_id, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'id'
2022-07-04 15:34:44 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:34:45 INFO-Watching for file changes with StatReloader
2022-07-04 15:35:32 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:35:32 INFO-Watching for file changes with StatReloader
2022-07-04 15:54:06 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:54:07 INFO-Watching for file changes with StatReloader
2022-07-04 15:57:13 WARNING-Method Not Allowed: /book/5/
2022-07-04 15:57:44 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 15:57:45 INFO-Watching for file changes with StatReloader
2022-07-04 15:57:56 WARNING-Method Not Allowed: /book/5/
2022-07-04 15:58:48 WARNING-Method Not Allowed: /book/5/
2022-07-04 16:02:45 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:02:46 INFO-Watching for file changes with StatReloader
2022-07-04 16:04:44 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:04:45 INFO-Watching for file changes with StatReloader
2022-07-04 16:09:59 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:10:00 INFO-Watching for file changes with StatReloader
2022-07-04 16:10:06 WARNING-Method Not Allowed: /book/5/
2022-07-04 16:12:32 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\serializers.py changed, reloading.
2022-07-04 16:12:33 INFO-Watching for file changes with StatReloader
2022-07-04 16:12:46 WARNING-Method Not Allowed: /book/5/
2022-07-04 16:14:57 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\serializers.py changed, reloading.
2022-07-04 16:14:58 INFO-Watching for file changes with StatReloader
2022-07-04 16:16:10 WARNING-Method Not Allowed: /book/5/
2022-07-04 16:20:16 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:20:17 INFO-Watching for file changes with StatReloader
2022-07-04 16:20:20 ERROR-Log Error Message
2022-07-04 16:20:42 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:20:43 INFO-Watching for file changes with StatReloader
2022-07-04 16:24:05 WARNING-Method Not Allowed: /book/5/
2022-07-04 16:28:28 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:28:28 INFO-Watching for file changes with StatReloader
2022-07-04 16:28:29 WARNING-Method Not Allowed: /book/5/
2022-07-04 16:28:31 WARNING-Method Not Allowed: /book/5/
2022-07-04 16:30:28 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py changed, reloading.
2022-07-04 16:30:28 INFO-Watching for file changes with StatReloader
2022-07-04 16:35:09 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:35:10 INFO-Watching for file changes with StatReloader
2022-07-04 16:35:24 WARNING-Method Not Allowed: /book/5/
2022-07-04 16:37:21 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:37:22 INFO-Watching for file changes with StatReloader
2022-07-04 16:37:59 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:38:00 INFO-Watching for file changes with StatReloader
2022-07-04 16:43:23 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:43:24 INFO-Watching for file changes with StatReloader
2022-07-04 16:43:30 ERROR-Log Error Message
2022-07-04 16:44:08 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:44:08 INFO-Watching for file changes with StatReloader
2022-07-04 16:44:09 ERROR-Log Error Message
2022-07-04 16:44:27 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:44:27 INFO-Watching for file changes with StatReloader
2022-07-04 16:44:58 ERROR-Log Error Message
2022-07-04 16:48:00 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:48:01 INFO-Watching for file changes with StatReloader
2022-07-04 16:48:02 ERROR-Log Error Message
2022-07-04 16:48:31 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:48:32 INFO-Watching for file changes with StatReloader
2022-07-04 16:48:32 ERROR-Log Error Message
2022-07-04 16:49:05 ERROR-Log Error Message
2022-07-04 16:52:26 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:52:26 INFO-Watching for file changes with StatReloader
2022-07-04 16:52:28 ERROR-Internal Server Error: /book/5/
Traceback (most recent call last):
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\common\jwt.py", line 30, in token_decode
    return f(request, user_id, *args, **kwargs)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py", line 56, in patch
    print(book_s.data)
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\The Lie Lama\PycharmProjects\address_book_django\venv\lib\site-packages\rest_framework\serializers.py", line 249, in data
    raise AssertionError(msg)
AssertionError: When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2022-07-04 16:53:02 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:53:02 INFO-Watching for file changes with StatReloader
2022-07-04 16:54:58 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:54:59 INFO-Watching for file changes with StatReloader
2022-07-04 16:57:09 INFO-C:\Users\The Lie Lama\PycharmProjects\address_book_django\book_store\books\views.py changed, reloading.
2022-07-04 16:57:10 INFO-Watching for file changes with StatReloader
